# Generated by Django 4.2.4 on 2023-08-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electrify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('units', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
